# Generated by Django 3.0.2 on 2020-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='defintion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='origin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='pos',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='shortdefinition',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='when',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
