# Generated by Django 3.0.2 on 2020-06-17 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20200617_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='defintion',
            new_name='definition',
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 12, 1, 15, 348168)),
        ),
    ]
