# Generated by Django 3.0.2 on 2020-06-17 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_auto_20200617_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
