# Generated by Django 3.0.2 on 2020-06-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0010_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usage',
            options={},
        ),
    ]
