# Generated by Django 3.0.7 on 2020-06-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0011_auto_20200618_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
