# Generated by Django 3.0.7 on 2020-06-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0012_userfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'verbose_name_plural': 'feedback'},
        ),
    ]
