# Generated by Django 3.0.7 on 2020-06-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0013_auto_20200623_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
