# Generated by Django 3.0.7 on 2020-06-23 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0014_auto_20200623_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
